name: Simple workflow

on:
  repository_dispatch:
    types: do-something

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print a message
        run: |
          echo "Hello, world!"
