name: Second Workflow

on:
  workflow_run:
    workflows: ["JSON POST Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.outputs.json_payload, '"VAR_REGION":"Yes"') }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get inputs
        run: |
          echo "second workflow is triggered bcz region is yes"
