name: Second Workflow

on:
  workflow_run:
    workflows: ["JSON POST Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.outputs.json_payload, '"VAR_REGION":"Yes"') }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Save JSON payload to file
        run: |
          echo "${{ github.event.workflow_run.outputs.json_payload }}" > payload.json

      - name: Send email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: JSON Payload from Workflow
          to: gouthamsneham@gmail.com
          from: Your Email
          body: Attached is the JSON payload from the first workflow.
          attachments: payload.json
